version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:

